###
### General
###
# Set Path
SYSTEM_PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
USER_PATH="$HOME/.pyenv/shims:$HOME/bin:$HOME/.local/bin:$HOME/.go/bin:$HOME/.node_modules/bin:$(ruby -e 'puts Gem.user_dir')/bin:$HOME/.carbo/bin:$HOME/.krew/bin"
export PATH="${SYSTEM_PATH}:${USER_PATH}"

# Environment
export EDITOR="nvim"
export VISUAL="nvim"
export GPG_TTY=$(tty) # avoid 'inappropriate ioctl error'
export XDG_DESKTOP_DIR="${HOME}/dwl"
export XDG_DOWNLOAD_DIR="${HOME}/dwl"

# Go
export GO111MODULE=on
export GOPATH="$HOME/.go"
export GOBIN="$GOPATH/bin"
export GOPROXY="https://proxy.golang.org,direct"
export GOCACHE=/home/sugar/.cache/go-build

# bat theme (TODO use export BATH_CONFIG_PATH="/path/to/bat.conf"))
# $ bat --list-themes | fzf --preview="bat --theme={} --color=always /path/to/file"
export BAT_THEME="Monokai Extended"

# npm global install directory inside user directory ($ npm install -g <pkg>)
export npm_config_prefix="~/.node_modules"

# GPG git signing
export GPG_TTY=$(tty)

# Systemd
export SYSTEMD_LESS=FRXMK # prevent truncating of long lines in journalctl
#export SYSTEMD_LOG_LEVEL=debug # more debugging info from systemd

# nvim debugging
export NVIM_LOG_FILE="$HOME/.local/share/nvim/log"
#export NVIM_PYTHON_LOG_FILE="$HOME/DEBUG_nvim_python"
#export NVIM_PYTHON_LOG_LEVEL=DEBUG



# History settings
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
HISTCONTROLE=ignoredups


###
### Oh-my-zsh
###
export ZSH=$HOME/.oh-my-zsh

# hyphen-insensitive completion.
HYPHEN_INSENSITIVE="true"

# disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# more themes (https://github.com/robbyrussell/oh-my-zsh/wiki/themes)
ZSH_THEME="sunaku"

# TODO explore oh-my-zsh plugins
# Activate plugins
plugins=(
    git
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh


###
### fzf
###
# Source fzf completion and key-bindings
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh

# Default command
# --preview option must be set explicitly
export FZF_DEFAULT_COMMAND="fd --type file --follow --hidden --exclude .git --color=always"
export FZF_DEFAULT_OPTS="--ansi --no-height --no-reverse --select-1 --exit-0 \
    --multi --preview='' --preview-window=right:70%:wrap \
    --bind=ctrl-d:page-down,ctrl-u:page-up,ctrl-g:top,alt-u:preview-up,alt-d:preview-down \
    --bind='ctrl-y:execute(echo \"{..}\" | xclip -in -sel clipboard)'"

# CTRL_T - file
export FZF_CTRL_T_COMMAND="fd --type file --follow --hidden --exclude .git --color=always"
export FZF_CTRL_T_OPTS="--preview='bat {..} --color always --line-range :200'"

# ALT_C - cd
export FZF_ALT_C_COMMAND="fd -t d --hidden --exclude .git --color=always"
export FZF_ALT_C_OPTS="--preview 'tree -L 3 -C {} | head -200' --preview-window=right:70%:wrap"

# CTRL_R - history
export FZF_CTRL_R_OPTS=""


###
### Aliases
###
# Source aliases, without expanding commands
# Always quote nested commands "$( ... )" , otherwise they are evaluated when sourcing
unsetopt aliases
source $HOME/.zshrc.d/aliases.sh
setopt aliases
