#!/usr/bin/env python

import random
import sys

CATS = [
    [
        r"    |\__/,|   (`\\",
        r"  _.|o o  |_   ) )",
        r"-(((---(((--------",
    ],
    [
        " \`*-.                    ",
        "  )  _`-.                 ",
        " .  : `. .                ",
        " : _   '  \               ",
        " ; *` _.   `*-._          ",
        " `-.-'          `-.       ",
        "   ;       `       `.     ",
        "   :.       .        \    ",
        "   . \  .   :   .-'   .   ",
        "   '  `+.;  ;  '      :   ",
        "   :  '  |    ;       ;-. ",
        "   ; '   : :`-:     _.`* ;",
        ".*' /  .*' ; .*`- +'  `*' ",
        "`*-*   `*-*  `*-*'",
    ],
    [
        "    ,_     _",
        "    |\\_,-~/",
        "    / _  _ |    ,--.",
        "   (  @  @ )   / ,-'",
        "    \  _T_/-._( (",
        "    /         `. \\",
        "   |         _  \ |",
        "    \ \ ,  /      |",
        "     || |-_\__   /",
        "    ((_/`(____,-'",
    ],
]


def main(msg):
    cat = random.choice(CATS)
    sep = "-" * len(msg)
    print(sep, "\n", msg, "\n", sep, "\n")
    for line in cat:
        print("\t", line)


if __name__ == "__main__":
    msg = " ".join(sys.argv[1:])
    if len(msg) == 0:
        print("Please provide a message. Exiting.", file=sys.stderr)
        sys.exit(1)
    main(msg)
